
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
#    - '**.gen.dart'

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
    directives_ordering: true
    prefer_const_constructors: true
    avoid_print: true
    