name: utilities
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-134.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  injectable: ^2.1.2
  get_it: ^7.6.0
  slang: ^3.19.0
  slang_flutter: ^3.19.0

dev_dependencies:
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  lints: ^2.0.0
  test: ^1.21.0
