name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-134.0.dev <4.0.0'

dependencies:
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  gotrue: ^1.9.0
  utilities:
    path: ../utilities

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  lints: ^2.0.0
  test: ^1.21.0
  mocktail:
